name: deploy-dev

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.GITHUB_OIDC_ROLE_NAME }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Bootstrap (create tfstate bucket + lock table)
        run: |
          terraform -chdir=bootstrap init
          terraform -chdir=bootstrap apply -auto-approve

      - name: Capture bootstrap outputs
        id: bs
        run: |
          echo "TFSTATE_BUCKET=$(terraform -chdir=bootstrap output -raw tfstate_bucket_name)" >> $GITHUB_ENV
          echo "LOCK_TABLE=$(terraform -chdir=bootstrap output -raw lock_table_name)" >> $GITHUB_ENV
          echo "AWS_REGION=$(terraform -chdir=bootstrap output -raw aws_region)" >> $GITHUB_ENV
          echo "SUFFIX=$(terraform -chdir=bootstrap output -raw suffix)" >> $GITHUB_ENV

      - name: Build Lambda package
        run: |
          chmod +x ./build-root.sh
          ./build-root.sh noplan

      - name: Terraform init (main backend to S3)
        run: |
          terraform init \
            -backend-config="bucket=${TFSTATE_BUCKET}" \
            -backend-config="dynamodb_table=${LOCK_TABLE}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="key=dev/terraform.tfstate"

      - name: Terraform apply (main)
        run: |
          terraform apply -auto-approve \
            -var="suffix=${SUFFIX}"
